 export const columns = [
    { field: "id", headerName: "Name", width: 200 },
    { field: "Date", headerName: "Date", width: 200 },
    { field: "Time", headerName: "Time", width: 200 },
    {
      field: "Keyword",
      headerName: "Keyword",
      type: "number",
      width: 200,
    },
    {
      field: "NotebookName",
      headerName: "NotebookName",
      width: 200,
    },
  ];
  export const rows = [
    {
      id: "Lannster",
      Date: "25 Jan 2022",
      Time: "10:10 PM",
      Keyword: "Webservice",
      NotebookName: "server.xml",
    },
    {
      id: "Lanniser",
      Date: "26 Jan 2022",
      Time: "11:20 PM",
      Keyword: "Webservice",
      NotebookName: "server.xml",
    },
    {
      id: "Lanniste",
      Date: "27 Jan 2022",
      Time: "12:30 AM",
      Keyword: "Webservice",
      NotebookName: "server.xml",
    },
    {
      id: "Lanister",
      img:"./pic.jpg",
      Date: "28 Jan 2022",
      Time: "1:10 AM",
      Keyword: "Webservice",
      NotebookName: "server.xml",
    },
    {
      id: "Lnnister",
      img:"./pic.jpg",
      Date: "29 Jan 2022",
      Time: "02:20 AM",
      Keyword: "Webservice",
      NotebookName: "server.xml",
    },
    {
      id: "Lannisr",
      img:"./pic.jpg",
      Date: "30 Jan 2022",
      Time: "03:30 AM",
      Keyword: "Webservice",
      NotebookName: "server.xml",
    },
    {
      id: "Laister",
      img:"./pic.jpg",
      Date: "31 Jan 2022",
      Time: "04:10 AM",
      Keyword: "Webservice",
      NotebookName: "server.xml",
    },
    {
      id: "Lannter",
      img:"./pic.jpg",
      Date: "1st Feb 2022",
      Time: "05:30 AM",
      Keyword: "Webservice",
      NotebookName: "server.xml",
    },
    {
      id: "Lannist",
      img:"./pic.jpg",
      Date: "2nd Feb 2022",
      Time: "06:40 AM",
      Keyword: "Webservice",
      NotebookName: "server.xml",
    },
  ];
 